//! FFI exports for PowerShell integration
//!
//! This module provides a C-compatible FFI interface for calling the pcai-inference
//! library from PowerShell via P/Invoke.
//!
//! # Safety
//!
//! All FFI functions accept raw pointers from C callers. The safety requirements are
//! documented on each function. This module allows `clippy::not_unsafe_ptr_arg_deref`
//! because marking FFI functions as `unsafe` doesn't help C/C#/PowerShell callers
//! who cannot see Rust's `unsafe` keyword.

#![allow(clippy::not_unsafe_ptr_arg_deref)]
//!
//! ## Thread Safety
//!
//! - Global state is protected by Mutex
//! - Runtime is created once and reused
//! - Errors are stored in thread-local storage
//!
//! ## Usage from PowerShell
//!
//! ```powershell
//! # Load the DLL
//! Add-Type -Path "pcai_inference.dll" -Namespace PCAI -Name Inference
//!
//! # Initialize with backend
//! [PCAI.Inference]::pcai_init("llamacpp")
//!
//! # Load model
//! [PCAI.Inference]::pcai_load_model("path/to/model.gguf", -1)
//!
//! # Generate text
//! $result = [PCAI.Inference]::pcai_generate("Hello", 100, 0.7)
//! $text = [System.Runtime.InteropServices.Marshal]::PtrToStringAnsi($result)
//! [PCAI.Inference]::pcai_free_string($result)
//! ```

use std::cell::RefCell;
use std::collections::HashMap;
use std::ffi::{CStr, CString};
use std::os::raw::{c_char, c_void};
use std::sync::atomic::{AtomicI64, Ordering as AtomicOrdering};
use std::sync::{Mutex, OnceLock};

use tokio::runtime::Runtime;

#[cfg(any(feature = "llamacpp", feature = "mistralrs-backend"))]
use crate::backends::BackendType;
use crate::backends::{GenerateRequest, InferenceBackend};
use crate::Error;

// ============================================================================
// Error Codes
// ============================================================================

/// Error codes returned by FFI functions
#[repr(i32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PcaiErrorCode {
    /// Operation succeeded
    Success = 0,
    /// Backend not initialized (call pcai_init first)
    NotInitialized = -1,
    /// Model not loaded (call pcai_load_model first)
    ModelNotLoaded = -2,
    /// Invalid input parameter (null pointer, invalid UTF-8, etc.)
    InvalidInput = -3,
    /// Backend operation failed
    BackendError = -4,
    /// I/O error (file not found, permission denied, etc.)
    IoError = -5,
    /// Unknown or unclassified error
    Unknown = -99,
}

impl PcaiErrorCode {
    /// Convert from i32 to PcaiErrorCode
    pub fn from_i32(code: i32) -> Self {
        match code {
            0 => Self::Success,
            -1 => Self::NotInitialized,
            -2 => Self::ModelNotLoaded,
            -3 => Self::InvalidInput,
            -4 => Self::BackendError,
            -5 => Self::IoError,
            _ => Self::Unknown,
        }
    }
}

// ============================================================================
// Async Request Tracking
// ============================================================================

/// Monotonically increasing request ID counter
static NEXT_REQUEST_ID: AtomicI64 = AtomicI64::new(1);

/// Status of an async inference request
enum RequestStatus {
    /// Request accepted, not yet picked up by worker thread
    Pending,
    /// Worker thread is actively running inference
    Running,
    /// Inference finished successfully
    Complete {
        text: String,
        tokens_generated: u32,
        prompt_tokens_estimated: u32,
    },
    /// Inference failed; text is the error message
    Failed(String),
    /// Request was cancelled before or during inference
    Cancelled,
}

/// Result of polling an async request
///
/// Returned by `pcai_poll_result`. When `status` is 2 (complete) or 3 (failed)
/// the `text` pointer is non-null and **must** be freed by the caller with
/// `pcai_free_string`. For all other statuses `text` is null.
#[repr(C)]
pub struct PcaiAsyncResult {
    /// 0 = pending, 1 = running, 2 = complete, 3 = failed, 4 = cancelled, -1 = unknown id
    pub status: i32,
    /// Result text. Only valid when `status` is 2 or 3. Caller must free with `pcai_free_string`.
    pub text: *mut c_char,
    /// Number of tokens generated by the backend. 0 if not available or not complete.
    pub tokens_generated: u32,
    /// Estimated prompt token count (heuristic: max(chars/4, words)). 0 if not available.
    pub prompt_tokens_estimated: u32,
}

// ============================================================================
// Global State
// ============================================================================

/// Global state holding the runtime, backend, and async request map
struct GlobalState {
    runtime: Runtime,
    backend: Option<Box<dyn InferenceBackend>>,
    requests: HashMap<i64, RequestStatus>,
}

/// Global state instance (initialized once)
static GLOBAL_STATE: OnceLock<Mutex<GlobalState>> = OnceLock::new();

// Thread-local error storage
thread_local! {
    static LAST_ERROR: RefCell<Option<String>> = const { RefCell::new(None) };
    static LAST_ERROR_CODE: RefCell<PcaiErrorCode> = const { RefCell::new(PcaiErrorCode::Success) };
    /// Reusable CString buffer for pcai_last_error. Avoids leaking memory on every call.
    static LAST_ERROR_CSTRING: RefCell<Option<CString>> = const { RefCell::new(None) };
}

/// Initialize global state on first access
fn init_global_state() -> &'static Mutex<GlobalState> {
    GLOBAL_STATE.get_or_init(|| {
        let runtime = Runtime::new().expect("Failed to create Tokio runtime");
        Mutex::new(GlobalState {
            runtime,
            backend: None,
            requests: HashMap::new(),
        })
    })
}

/// Set the last error with a specific error code
fn set_last_error_with_code(err: impl Into<String>, code: PcaiErrorCode) {
    LAST_ERROR.with(|e| {
        *e.borrow_mut() = Some(err.into());
    });
    LAST_ERROR_CODE.with(|c| {
        *c.borrow_mut() = code;
    });
}

/// Set the last error message with the `Unknown` error code
#[cfg(test)]
fn set_last_error(err: impl Into<String>) {
    set_last_error_with_code(err, PcaiErrorCode::Unknown);
}

/// Clear the last error for the current thread
fn clear_last_error() {
    LAST_ERROR.with(|e| {
        *e.borrow_mut() = None;
    });
    LAST_ERROR_CODE.with(|c| {
        *c.borrow_mut() = PcaiErrorCode::Success;
    });
}

/// Get a C string from a raw pointer, handling null safely
unsafe fn c_str_from_ptr<'a>(ptr: *const c_char) -> Result<&'a str, Error> {
    if ptr.is_null() {
        return Err(Error::InvalidInput("Null pointer".to_string()));
    }
    CStr::from_ptr(ptr)
        .to_str()
        .map_err(|e| Error::InvalidInput(format!("Invalid UTF-8: {}", e)))
}

/// Estimate prompt token count using a heuristic (max of chars/4 and word count).
/// This matches the HTTP server's `estimate_tokens` function.
fn estimate_prompt_tokens(text: &str) -> u32 {
    if text.is_empty() {
        return 0;
    }
    let char_tokens = text.chars().count().div_ceil(4);
    let word_tokens = text.split_whitespace().count();
    char_tokens.max(word_tokens).max(1) as u32
}

// ============================================================================
// FFI Exports
// ============================================================================

/// Initialize the inference backend
///
/// # Arguments
/// * `backend_name` - Backend to use: "llamacpp" or "mistralrs"
///
/// # Returns
/// * 0 on success
/// * -1 on error (check pcai_last_error)
///
/// # Safety
/// * `backend_name` must be a valid null-terminated C string
/// * Must be called before any other functions except pcai_last_error
#[no_mangle]
pub extern "C" fn pcai_init(backend_name: *const c_char) -> i32 {
    clear_last_error();

    // Parse backend name
    let backend_str = match unsafe { c_str_from_ptr(backend_name) } {
        Ok(s) => s,
        Err(e) => {
            set_last_error_with_code(format!("Invalid backend name: {}", e), PcaiErrorCode::InvalidInput);
            return PcaiErrorCode::InvalidInput as i32;
        }
    };

    // Determine backend type
    #[cfg(not(any(feature = "llamacpp", feature = "mistralrs-backend")))]
    {
        set_last_error_with_code(
            format!(
                "Unknown backend: {}. No backend features enabled. Enable 'llamacpp' or 'mistralrs-backend' feature.",
                backend_str
            ),
            PcaiErrorCode::InvalidInput,
        );
        PcaiErrorCode::InvalidInput as i32
    }

    #[cfg(any(feature = "llamacpp", feature = "mistralrs-backend"))]
    let backend_type: BackendType = match backend_str.to_lowercase().as_str() {
        #[cfg(feature = "llamacpp")]
        "llamacpp" | "llama.cpp" | "llama_cpp" => BackendType::LlamaCpp,

        #[cfg(feature = "mistralrs-backend")]
        "mistralrs" | "mistral.rs" | "mistral_rs" => BackendType::MistralRs,

        _ => {
            set_last_error_with_code(format!("Unknown backend: {}", backend_str), PcaiErrorCode::InvalidInput);
            return PcaiErrorCode::InvalidInput as i32;
        }
    };

    // Initialize global state and create backend
    #[cfg(any(feature = "llamacpp", feature = "mistralrs-backend"))]
    {
        let state = init_global_state();
        let mut guard = match state.lock() {
            Ok(g) => g,
            Err(e) => {
                set_last_error_with_code(format!("Failed to lock state: {}", e), PcaiErrorCode::BackendError);
                return PcaiErrorCode::BackendError as i32;
            }
        };

        // Create backend
        let backend = match backend_type.create() {
            Ok(b) => b,
            Err(e) => {
                set_last_error_with_code(format!("Failed to create backend: {}", e), PcaiErrorCode::BackendError);
                return PcaiErrorCode::BackendError as i32;
            }
        };

        guard.backend = Some(backend);
        tracing::info!("Initialized backend: {}", backend_str);

        PcaiErrorCode::Success as i32
    }
}

/// Load a model into the active backend
///
/// # Arguments
/// * `model_path` - Path to the model file (GGUF or SafeTensors)
/// * `gpu_layers` - Number of layers to offload to GPU (-1 = all, 0 = CPU only)
///
/// # Returns
/// * 0 on success
/// * -1 on error (check pcai_last_error)
///
/// # Safety
/// * `model_path` must be a valid null-terminated C string
/// * Must call pcai_init first
#[no_mangle]
pub extern "C" fn pcai_load_model(model_path: *const c_char, gpu_layers: i32) -> i32 {
    clear_last_error();

    // Parse model path
    let path_str = match unsafe { c_str_from_ptr(model_path) } {
        Ok(s) => s.to_string(),
        Err(e) => {
            set_last_error_with_code(format!("Invalid model path: {}", e), PcaiErrorCode::InvalidInput);
            return PcaiErrorCode::InvalidInput as i32;
        }
    };

    // Get global state
    let state = init_global_state();
    let mut guard = match state.lock() {
        Ok(g) => g,
        Err(e) => {
            set_last_error_with_code(format!("Failed to lock state: {}", e), PcaiErrorCode::BackendError);
            return PcaiErrorCode::BackendError as i32;
        }
    };

    // For llamacpp backend, we need to recreate it with the right gpu_layers config
    // This is a limitation of the current backend design - do this before loading
    #[cfg(feature = "llamacpp")]
    {
        if let Some(backend) = guard.backend.as_ref() {
            if backend.backend_name() == "llama.cpp" {
                use crate::backends::llamacpp::LlamaCppBackend;

                let n_gpu_layers = if gpu_layers < 0 {
                    u32::MAX // All layers
                } else {
                    gpu_layers as u32
                };

                let new_backend = LlamaCppBackend::with_config(n_gpu_layers, 8192, 2048);
                guard.backend = Some(Box::new(new_backend));
            }
        }
    }
    #[cfg(not(feature = "llamacpp"))]
    {
        let _ = gpu_layers; // Suppress unused warning
    }

    // Check backend exists
    if guard.backend.is_none() {
        set_last_error_with_code(
            "Backend not initialized. Call pcai_init first.",
            PcaiErrorCode::NotInitialized,
        );
        return PcaiErrorCode::NotInitialized as i32;
    }

    // Load the model (async operation, block on runtime)
    // Split mutable reference to satisfy borrow checker
    let GlobalState { runtime, backend, .. } = &mut *guard;

    if let Some(backend) = backend {
        let result = runtime.block_on(async { backend.load_model(&path_str).await });

        match result {
            Ok(_) => {
                tracing::info!("Model loaded: {}", path_str);
                PcaiErrorCode::Success as i32
            }
            Err(e) => {
                // Classify error type
                let error_code = if e.to_string().contains("not found")
                    || e.to_string().contains("No such file")
                    || e.to_string().contains("cannot open")
                {
                    PcaiErrorCode::IoError
                } else {
                    PcaiErrorCode::BackendError
                };
                set_last_error_with_code(format!("Failed to load model: {}", e), error_code);
                error_code as i32
            }
        }
    } else {
        set_last_error_with_code(
            "Backend not initialized. Call pcai_init first.",
            PcaiErrorCode::NotInitialized,
        );
        PcaiErrorCode::NotInitialized as i32
    }
}

/// Generate text from a prompt
///
/// # Arguments
/// * `prompt` - Input text prompt (max 100KB)
/// * `max_tokens` - Maximum tokens to generate (0 = default 512)
/// * `temperature` - Sampling temperature (0.0 = greedy, 1.0 = creative)
///
/// # Returns
/// * Pointer to generated text (caller must free with pcai_free_string)
/// * null on error (check pcai_last_error)
///
/// # Safety
/// * `prompt` must be a valid null-terminated C string
/// * Caller must free the returned string with pcai_free_string
/// * Must call pcai_load_model first
#[no_mangle]
pub extern "C" fn pcai_generate(prompt: *const c_char, max_tokens: u32, temperature: f32) -> *mut c_char {
    clear_last_error();

    // Parse prompt
    let prompt_str = match unsafe { c_str_from_ptr(prompt) } {
        Ok(s) => s,
        Err(e) => {
            set_last_error_with_code(format!("Invalid prompt: {}", e), PcaiErrorCode::InvalidInput);
            return std::ptr::null_mut();
        }
    };

    // Validate prompt length (100KB max to prevent DoS)
    const MAX_PROMPT_SIZE: usize = 100 * 1024; // 100KB
    if prompt_str.len() > MAX_PROMPT_SIZE {
        set_last_error_with_code(
            format!("Prompt too large: {} bytes (max {})", prompt_str.len(), MAX_PROMPT_SIZE),
            PcaiErrorCode::InvalidInput,
        );
        return std::ptr::null_mut();
    }

    // Get global state
    let state = init_global_state();
    let guard = match state.lock() {
        Ok(g) => g,
        Err(e) => {
            set_last_error_with_code(format!("Failed to lock state: {}", e), PcaiErrorCode::BackendError);
            return std::ptr::null_mut();
        }
    };

    // Check backend exists
    let backend = match guard.backend.as_ref() {
        Some(b) => b,
        None => {
            set_last_error_with_code(
                "Backend not initialized. Call pcai_init first.",
                PcaiErrorCode::NotInitialized,
            );
            return std::ptr::null_mut();
        }
    };

    // Check model loaded
    if !backend.is_loaded() {
        set_last_error_with_code(
            "Model not loaded. Call pcai_load_model first.",
            PcaiErrorCode::ModelNotLoaded,
        );
        return std::ptr::null_mut();
    }

    // Build request
    let request = GenerateRequest {
        prompt: prompt_str.to_string(),
        max_tokens: if max_tokens > 0 {
            Some(max_tokens as usize)
        } else {
            None
        },
        temperature: if temperature > 0.0 { Some(temperature) } else { None },
        top_p: None,
        stop: vec![],
    };

    // Generate (async operation, block on runtime)
    let result = guard.runtime.block_on(async { backend.generate(request).await });

    match result {
        Ok(response) => {
            tracing::debug!("Generated {} tokens", response.tokens_generated);

            // Convert to C string
            match CString::new(response.text) {
                Ok(c_str) => c_str.into_raw(),
                Err(e) => {
                    set_last_error_with_code(format!("Failed to create C string: {}", e), PcaiErrorCode::BackendError);
                    std::ptr::null_mut()
                }
            }
        }
        Err(e) => {
            set_last_error_with_code(format!("Generation failed: {}", e), PcaiErrorCode::BackendError);
            std::ptr::null_mut()
        }
    }
}

/// Callback function type for streaming generation
///
/// # Arguments
/// * `token` - Generated token text (null-terminated C string)
/// * `user_data` - User-provided data pointer
///
/// # Safety
/// * Callback must not panic
/// * Callback must not call back into pcai functions
pub type TokenCallback = extern "C" fn(token: *const c_char, user_data: *mut c_void);

/// Generate text with streaming callback
///
/// # Arguments
/// * `prompt` - Input text prompt
/// * `max_tokens` - Maximum tokens to generate (0 = default 512)
/// * `temperature` - Sampling temperature (0.0 = greedy, 1.0 = creative)
/// * `callback` - Function to call for each generated token
/// * `user_data` - Pointer to pass to callback
///
/// # Returns
/// * 0 on success
/// * -1 on error (check pcai_last_error)
///
/// # Safety
/// * `prompt` must be a valid null-terminated C string
/// * `callback` must be a valid function pointer
/// * `user_data` can be null
/// * Callback must not call back into pcai functions
/// * Must call pcai_load_model first
#[no_mangle]
#[expect(
    unused_variables,
    reason = "FFI boundary parameters required by the C ABI contract; some are unused when the llamacpp feature is disabled"
)]
pub extern "C" fn pcai_generate_streaming(
    prompt: *const c_char,
    max_tokens: u32,
    temperature: f32,
    callback: TokenCallback,
    user_data: *mut c_void,
) -> i32 {
    clear_last_error();

    // Parse prompt
    let prompt_str = match unsafe { c_str_from_ptr(prompt) } {
        Ok(s) => s,
        Err(e) => {
            set_last_error_with_code(format!("Invalid prompt: {}", e), PcaiErrorCode::InvalidInput);
            return PcaiErrorCode::InvalidInput as i32;
        }
    };

    // Validate prompt length (100KB max to prevent DoS)
    const MAX_PROMPT_SIZE: usize = 100 * 1024; // 100KB
    if prompt_str.len() > MAX_PROMPT_SIZE {
        set_last_error_with_code(
            format!("Prompt too large: {} bytes (max {})", prompt_str.len(), MAX_PROMPT_SIZE),
            PcaiErrorCode::InvalidInput,
        );
        return PcaiErrorCode::InvalidInput as i32;
    }

    let prompt_str = prompt_str.to_string();

    // Get global state
    let state = init_global_state();
    let guard = match state.lock() {
        Ok(g) => g,
        Err(e) => {
            set_last_error_with_code(format!("Failed to lock state: {}", e), PcaiErrorCode::BackendError);
            return PcaiErrorCode::BackendError as i32;
        }
    };

    // Check backend exists
    let backend = match guard.backend.as_ref() {
        Some(b) => b,
        None => {
            set_last_error_with_code(
                "Backend not initialized. Call pcai_init first.",
                PcaiErrorCode::NotInitialized,
            );
            return PcaiErrorCode::NotInitialized as i32;
        }
    };

    // Check model loaded
    if !backend.is_loaded() {
        set_last_error_with_code(
            "Model not loaded. Call pcai_load_model first.",
            PcaiErrorCode::ModelNotLoaded,
        );
        return PcaiErrorCode::ModelNotLoaded as i32;
    }

    // Build request
    let request = GenerateRequest {
        prompt: prompt_str,
        max_tokens: if max_tokens > 0 {
            Some(max_tokens as usize)
        } else {
            None
        },
        temperature: if temperature > 0.0 { Some(temperature) } else { None },
        top_p: None,
        stop: vec![],
    };

    // Generate with streaming (backend-specific implementation)
    // SAFETY: We convert the pointer to usize to make it Send-safe across the async boundary.
    // This is safe because we're using block_on (not spawning a separate thread) and the
    // callback/user_data are assumed valid for the duration of this call.
    let user_data_addr = user_data as usize;
    let result = guard.runtime.block_on(async move {
        let mut bridge = move |token: String| {
            if let Ok(c_token) = CString::new(token) {
                // SAFETY: We're reconstructing the pointer from the address we saved earlier.
                // The caller must ensure the pointer remains valid for the duration of this call.
                let user_data_ptr = user_data_addr as *mut c_void;
                callback(c_token.as_ptr(), user_data_ptr);
            }
        };
        backend.generate_streaming(request, &mut bridge).await
    });

    match result {
        Ok(response) => {
            tracing::debug!("Streaming completed: {} tokens", response.tokens_generated);
            PcaiErrorCode::Success as i32
        }
        Err(e) => {
            set_last_error_with_code(
                format!("Streaming generation failed: {}", e),
                PcaiErrorCode::BackendError,
            );
            PcaiErrorCode::BackendError as i32
        }
    }
}

/// Free a string returned by pcai_generate
///
/// # Arguments
/// * `s` - String pointer returned by pcai_generate
///
/// # Safety
/// * `s` must be a pointer returned by pcai_generate or null
/// * Must not be called twice on the same pointer
#[no_mangle]
pub extern "C" fn pcai_free_string(s: *mut c_char) {
    if s.is_null() {
        return;
    }

    // SAFETY: `s` is non-null (checked above) and was produced by `CString::into_raw`
    // inside `pcai_generate`. Ownership is transferred back here so the allocation is
    // freed exactly once. The caller must not use `s` after this call.
    unsafe {
        let _ = CString::from_raw(s);
    }
}

/// Shutdown the inference engine and free resources
///
/// # Safety
/// * After calling this, all other functions will fail until pcai_init is called again
#[no_mangle]
pub extern "C" fn pcai_shutdown() {
    clear_last_error();

    let state = init_global_state();
    let mut guard = match state.lock() {
        Ok(g) => g,
        Err(e) => {
            set_last_error_with_code(format!("Failed to lock state: {}", e), PcaiErrorCode::BackendError);
            return;
        }
    };

    if let Some(mut backend) = guard.backend.take() {
        // Unload model
        let _ = guard.runtime.block_on(async { backend.unload_model().await });

        tracing::info!("Backend shutdown");
    }
}

/// Check if a backend has been initialized.
///
/// # Returns
/// * 1 if initialized
/// * 0 if not initialized or on error
#[no_mangle]
pub extern "C" fn pcai_is_initialized() -> i32 {
    let state = init_global_state();
    let guard = match state.lock() {
        Ok(g) => g,
        Err(_) => return 0,
    };

    if guard.backend.is_some() {
        1
    } else {
        0
    }
}

/// Check if a model is loaded in the active backend.
///
/// # Returns
/// * 1 if a model is loaded
/// * 0 if not loaded or on error
#[no_mangle]
pub extern "C" fn pcai_is_model_loaded() -> i32 {
    let state = init_global_state();
    let guard = match state.lock() {
        Ok(g) => g,
        Err(_) => return 0,
    };

    match guard.backend.as_ref() {
        Some(backend) if backend.is_loaded() => 1,
        _ => 0,
    }
}

/// Get the name of the active backend.
///
/// # Returns
/// * Pointer to a static string ("llama.cpp" or "mistral.rs")
/// * null if no backend is initialized
///
/// # Safety
/// * Returned pointer is valid for the lifetime of the program
/// * Do NOT call pcai_free_string on this pointer
#[no_mangle]
pub extern "C" fn pcai_get_backend_name() -> *const c_char {
    static LLAMA_CPP: &str = "llama.cpp\0";
    static MISTRAL_RS: &str = "mistral.rs\0";

    let state = init_global_state();
    let guard = match state.lock() {
        Ok(g) => g,
        Err(_) => return std::ptr::null(),
    };

    let backend = match guard.backend.as_ref() {
        Some(b) => b,
        None => return std::ptr::null(),
    };

    match backend.backend_name() {
        "llama.cpp" => LLAMA_CPP.as_ptr() as *const c_char,
        "mistral.rs" => MISTRAL_RS.as_ptr() as *const c_char,
        _ => std::ptr::null(),
    }
}

/// Get the last error message for the current thread
///
/// # Returns
/// * Pointer to error message (do NOT free)
/// * null if no error
///
/// # Safety
/// * Returned pointer is valid until the next call to any pcai function
///   on the same thread
/// * Do NOT call pcai_free_string on this pointer
#[no_mangle]
pub extern "C" fn pcai_last_error() -> *const c_char {
    LAST_ERROR.with(|e| {
        let err_ref = e.borrow();
        match err_ref.as_ref() {
            Some(err) => {
                // Store the CString in a thread-local buffer so the pointer
                // remains valid until the next call. This avoids the memory
                // leak that std::mem::forget would cause.
                match CString::new(err.as_str()) {
                    Ok(c_str) => {
                        let ptr = c_str.as_ptr();
                        LAST_ERROR_CSTRING.with(|buf| {
                            *buf.borrow_mut() = Some(c_str);
                        });
                        ptr
                    }
                    Err(_) => std::ptr::null(),
                }
            }
            None => std::ptr::null(),
        }
    })
}

/// Get the error code for the last error
///
/// # Returns
/// * Error code as i32 (see PcaiErrorCode enum)
/// * 0 if no error (Success)
#[no_mangle]
pub extern "C" fn pcai_last_error_code() -> i32 {
    LAST_ERROR_CODE.with(|c| *c.borrow() as i32)
}

/// Get the crate version string
///
/// # Returns
/// * Pointer to version string (do NOT free)
///
/// # Safety
/// * Returned pointer is valid for the lifetime of the program
/// * Do NOT call pcai_free_string on this pointer
#[no_mangle]
pub extern "C" fn pcai_version() -> *const c_char {
    static VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), "\0");
    VERSION.as_ptr() as *const c_char
}

/// Submit an asynchronous generation request
///
/// Spawns a background OS thread that calls the active backend and stores the
/// result in the global request map. The caller must poll with
/// `pcai_poll_result` and eventually receive a terminal status (complete,
/// failed, or cancelled) which removes the entry from the map.
///
/// # Arguments
/// * `prompt` - Input text prompt (null-terminated C string, max 100 KB)
/// * `max_tokens` - Maximum tokens to generate (0 = backend default)
/// * `temperature` - Sampling temperature (0.0 = greedy, 1.0 = creative)
///
/// # Returns
/// * Request ID > 0 on success
/// * -1 on error (check `pcai_last_error`)
///
/// # Safety
/// * `prompt` must be a valid null-terminated C string
/// * Must call `pcai_load_model` before submitting requests
#[no_mangle]
pub extern "C" fn pcai_generate_async(prompt: *const c_char, max_tokens: u32, temperature: f32) -> i64 {
    clear_last_error();

    let prompt_str = match unsafe { c_str_from_ptr(prompt) } {
        Ok(s) => s.to_string(),
        Err(_) => {
            set_last_error_with_code("Invalid prompt string", PcaiErrorCode::InvalidInput);
            return -1;
        }
    };

    // Validate prompt length (100 KB max)
    const MAX_PROMPT_SIZE: usize = 100 * 1024;
    if prompt_str.len() > MAX_PROMPT_SIZE {
        set_last_error_with_code(
            format!("Prompt too large: {} bytes (max {})", prompt_str.len(), MAX_PROMPT_SIZE),
            PcaiErrorCode::InvalidInput,
        );
        return -1;
    }

    // Validate backend is ready before allocating an ID
    {
        let state = init_global_state();
        let guard = match state.lock() {
            Ok(g) => g,
            Err(e) => {
                set_last_error_with_code(format!("Failed to lock state: {}", e), PcaiErrorCode::BackendError);
                return -1;
            }
        };

        if guard.backend.is_none() {
            set_last_error_with_code(
                "Backend not initialized. Call pcai_init first.",
                PcaiErrorCode::NotInitialized,
            );
            return -1;
        }

        let backend = guard.backend.as_ref().expect("backend is_none was checked above");
        if !backend.is_loaded() {
            set_last_error_with_code(
                "Model not loaded. Call pcai_load_model first.",
                PcaiErrorCode::ModelNotLoaded,
            );
            return -1;
        }
    }

    // Allocate a unique request ID and register it as Pending
    let id = NEXT_REQUEST_ID.fetch_add(1, AtomicOrdering::SeqCst);
    {
        let state = init_global_state();
        if let Ok(mut g) = state.lock() {
            g.requests.insert(id, RequestStatus::Pending);
        }
    }

    // Spawn a plain OS thread so we can call `runtime.block_on` without risk
    // of nesting a blocking call inside the Tokio thread pool.
    std::thread::spawn(move || {
        // Transition: Pending -> Running (unless already cancelled)
        {
            let state = init_global_state();
            if let Ok(mut g) = state.lock() {
                match g.requests.get(&id) {
                    Some(RequestStatus::Cancelled) => return,
                    _ => {
                        g.requests.insert(id, RequestStatus::Running);
                    }
                }
            }
        }

        // Build the request and run inference while holding the lock so that
        // the borrow checker can split `runtime` and `backend` simultaneously.
        let result = {
            let state = init_global_state();
            let mut guard = match state.lock() {
                Ok(g) => g,
                Err(e) => {
                    if let Ok(mut g2) = init_global_state().lock() {
                        g2.requests
                            .insert(id, RequestStatus::Failed(format!("Lock failed: {}", e)));
                    }
                    return;
                }
            };

            // Check for cancellation again before starting expensive work
            if matches!(guard.requests.get(&id), Some(RequestStatus::Cancelled)) {
                return;
            }

            // Estimate prompt tokens before sending to backend
            let prompt_tokens_est = estimate_prompt_tokens(&prompt_str);

            let req = GenerateRequest {
                prompt: prompt_str,
                max_tokens: if max_tokens > 0 {
                    Some(max_tokens as usize)
                } else {
                    None
                },
                temperature: if temperature > 0.0 { Some(temperature) } else { None },
                top_p: None,
                stop: vec![],
            };

            // Split borrow: `runtime` and `backend` are separate fields.
            let GlobalState { runtime, backend, .. } = &mut *guard;
            match backend.as_ref() {
                Some(b) => runtime.block_on(b.generate(req)),
                None => Err(crate::Error::InvalidInput("Backend not initialized".to_string())),
            }
        };

        // Store the terminal status
        if let Ok(mut g) = init_global_state().lock() {
            // Respect a late cancellation
            if matches!(g.requests.get(&id), Some(RequestStatus::Cancelled)) {
                return;
            }
            match result {
                Ok(response) => {
                    g.requests.insert(
                        id,
                        RequestStatus::Complete {
                            text: response.text,
                            tokens_generated: response.tokens_generated as u32,
                            prompt_tokens_estimated: prompt_tokens_est,
                        },
                    );
                }
                Err(e) => {
                    g.requests.insert(id, RequestStatus::Failed(format!("{}", e)));
                }
            }
        }
    });

    id
}

/// Poll the status of an async request
///
/// When the returned `status` is 2 (complete) or 3 (failed) the request is
/// removed from the internal map and the `text` pointer is non-null. The
/// caller **must** free it with `pcai_free_string`.
///
/// Status codes:
/// * 0 = pending
/// * 1 = running
/// * 2 = complete (`text` contains the generated output)
/// * 3 = failed (`text` contains the error message)
/// * 4 = cancelled
/// * -1 = unknown request ID
///
/// # Arguments
/// * `request_id` - ID returned by `pcai_generate_async`
///
/// # Safety
/// * Caller must free the returned `text` with `pcai_free_string` when
///   `status` is 2 or 3.
#[no_mangle]
pub extern "C" fn pcai_poll_result(request_id: i64) -> PcaiAsyncResult {
    let state = init_global_state();
    let mut guard = match state.lock() {
        Ok(g) => g,
        Err(_) => {
            return PcaiAsyncResult {
                status: -1,
                text: std::ptr::null_mut(),
                tokens_generated: 0,
                prompt_tokens_estimated: 0,
            };
        }
    };

    match guard.requests.get(&request_id) {
        Some(RequestStatus::Pending) => PcaiAsyncResult {
            status: 0,
            text: std::ptr::null_mut(),
            tokens_generated: 0,
            prompt_tokens_estimated: 0,
        },
        Some(RequestStatus::Running) => PcaiAsyncResult {
            status: 1,
            text: std::ptr::null_mut(),
            tokens_generated: 0,
            prompt_tokens_estimated: 0,
        },
        Some(RequestStatus::Complete { .. }) => {
            if let Some(RequestStatus::Complete {
                text,
                tokens_generated,
                prompt_tokens_estimated,
            }) = guard.requests.remove(&request_id)
            {
                let c_str = CString::new(text.replace('\0', "\u{FFFD}")).unwrap_or_default();
                PcaiAsyncResult {
                    status: 2,
                    text: c_str.into_raw(),
                    tokens_generated,
                    prompt_tokens_estimated,
                }
            } else {
                PcaiAsyncResult {
                    status: -1,
                    text: std::ptr::null_mut(),
                    tokens_generated: 0,
                    prompt_tokens_estimated: 0,
                }
            }
        }
        Some(RequestStatus::Failed(_)) => {
            if let Some(RequestStatus::Failed(text)) = guard.requests.remove(&request_id) {
                let c_str = CString::new(text.replace('\0', "\u{FFFD}")).unwrap_or_default();
                PcaiAsyncResult {
                    status: 3,
                    text: c_str.into_raw(),
                    tokens_generated: 0,
                    prompt_tokens_estimated: 0,
                }
            } else {
                PcaiAsyncResult {
                    status: -1,
                    text: std::ptr::null_mut(),
                    tokens_generated: 0,
                    prompt_tokens_estimated: 0,
                }
            }
        }
        Some(RequestStatus::Cancelled) => {
            guard.requests.remove(&request_id);
            PcaiAsyncResult {
                status: 4,
                text: std::ptr::null_mut(),
                tokens_generated: 0,
                prompt_tokens_estimated: 0,
            }
        }
        None => PcaiAsyncResult {
            status: -1,
            text: std::ptr::null_mut(),
            tokens_generated: 0,
            prompt_tokens_estimated: 0,
        },
    }
}

/// Cancel a pending or running async request
///
/// Marks the request as cancelled. If inference is already in progress the
/// worker thread will observe the flag before storing a result and will exit
/// without writing to the map. The cancelled entry is cleaned up by the next
/// call to `pcai_poll_result` for that ID.
///
/// # Arguments
/// * `request_id` - ID returned by `pcai_generate_async`
///
/// # Returns
/// * 0 if the request was successfully marked as cancelled
/// * -1 if the request ID was not found or the request had already finished
#[no_mangle]
pub extern "C" fn pcai_cancel(request_id: i64) -> i32 {
    let state = init_global_state();
    let mut guard = match state.lock() {
        Ok(g) => g,
        Err(_) => return -1,
    };

    match guard.requests.get_mut(&request_id) {
        Some(status @ RequestStatus::Pending) | Some(status @ RequestStatus::Running) => {
            *status = RequestStatus::Cancelled;
            0
        }
        _ => -1,
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_error_code_enum() {
        // Test enum values
        assert_eq!(PcaiErrorCode::Success as i32, 0);
        assert_eq!(PcaiErrorCode::NotInitialized as i32, -1);
        assert_eq!(PcaiErrorCode::ModelNotLoaded as i32, -2);
        assert_eq!(PcaiErrorCode::InvalidInput as i32, -3);
        assert_eq!(PcaiErrorCode::BackendError as i32, -4);
        assert_eq!(PcaiErrorCode::IoError as i32, -5);
        assert_eq!(PcaiErrorCode::Unknown as i32, -99);

        // Test from_i32
        assert_eq!(PcaiErrorCode::from_i32(0), PcaiErrorCode::Success);
        assert_eq!(PcaiErrorCode::from_i32(-1), PcaiErrorCode::NotInitialized);
        assert_eq!(PcaiErrorCode::from_i32(-2), PcaiErrorCode::ModelNotLoaded);
        assert_eq!(PcaiErrorCode::from_i32(-3), PcaiErrorCode::InvalidInput);
        assert_eq!(PcaiErrorCode::from_i32(-4), PcaiErrorCode::BackendError);
        assert_eq!(PcaiErrorCode::from_i32(-5), PcaiErrorCode::IoError);
        assert_eq!(PcaiErrorCode::from_i32(-99), PcaiErrorCode::Unknown);
        assert_eq!(PcaiErrorCode::from_i32(-1000), PcaiErrorCode::Unknown);
    }

    #[test]
    fn test_version() {
        let version_ptr = pcai_version();
        assert!(!version_ptr.is_null());

        let version_str = unsafe { CStr::from_ptr(version_ptr) };
        let version = version_str
            .to_str()
            .expect("test: version string from pcai_version must be valid UTF-8");

        // Version should be non-empty and match CARGO_PKG_VERSION
        assert!(!version.is_empty());
        assert_eq!(version, env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn test_error_storage() {
        clear_last_error();
        assert!(pcai_last_error().is_null());
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::Success as i32);

        set_last_error("test error");
        let err_ptr = pcai_last_error();
        assert!(!err_ptr.is_null());

        let err_str = unsafe { CStr::from_ptr(err_ptr) };
        assert_eq!(err_str.to_str().unwrap(), "test error");
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::Unknown as i32);

        clear_last_error();
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::Success as i32);
    }

    #[test]
    fn test_error_code_storage() {
        clear_last_error();
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::Success as i32);

        set_last_error_with_code("test error", PcaiErrorCode::InvalidInput);
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::InvalidInput as i32);

        set_last_error_with_code("backend error", PcaiErrorCode::BackendError);
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::BackendError as i32);

        clear_last_error();
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::Success as i32);
    }

    #[test]
    fn test_init_null_backend() {
        let result = pcai_init(std::ptr::null());
        assert_eq!(result, PcaiErrorCode::InvalidInput as i32);
        assert!(!pcai_last_error().is_null());
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::InvalidInput as i32);
    }

    #[test]
    fn test_generate_before_init() {
        // Reset state by calling shutdown
        pcai_shutdown();

        let prompt = CString::new("test").expect("test: CString::new must not fail for a simple ASCII prompt");
        let result = pcai_generate(prompt.as_ptr(), 10, 0.7);
        assert!(result.is_null());
        assert!(!pcai_last_error().is_null());
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::NotInitialized as i32);
    }

    #[test]
    fn test_prompt_length_validation() {
        pcai_shutdown();

        // Create a prompt larger than 100KB
        let large_prompt = "x".repeat(101 * 1024);
        let prompt_cstr =
            CString::new(large_prompt).expect("test: CString::new must not fail for a repeated-ASCII oversized prompt");

        let result = pcai_generate(prompt_cstr.as_ptr(), 10, 0.7);
        assert!(result.is_null());

        let err_ptr = pcai_last_error();
        assert!(!err_ptr.is_null());

        let err_str = unsafe { CStr::from_ptr(err_ptr) };
        let err_text = err_str
            .to_str()
            .expect("test: error string from pcai_last_error must be valid UTF-8");

        // Error should mention prompt size
        assert!(
            err_text.contains("too large") || err_text.contains("Prompt"),
            "Error should mention prompt size: {}",
            err_text
        );
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::InvalidInput as i32);
    }

    // -------------------------------------------------------------------------
    // Async FFI tests (no backend required – these test the bookkeeping layer)
    // -------------------------------------------------------------------------

    #[test]
    fn test_async_generate_before_init() {
        // Reset state
        pcai_shutdown();

        let prompt = CString::new("hello").expect("test: CString::new must not fail for a simple ASCII prompt");
        let id = pcai_generate_async(prompt.as_ptr(), 10, 0.7);
        assert_eq!(id, -1, "Should fail when no backend is initialised");
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::NotInitialized as i32);
    }

    #[test]
    fn test_async_generate_null_prompt() {
        let id = pcai_generate_async(std::ptr::null(), 10, 0.7);
        assert_eq!(id, -1, "Should fail on null prompt");
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::InvalidInput as i32);
    }

    #[test]
    fn test_async_generate_prompt_too_large() {
        let large = "x".repeat(101 * 1024);
        let cstr = CString::new(large).expect("test: CString::new must not fail for a repeated-ASCII oversized prompt");
        let id = pcai_generate_async(cstr.as_ptr(), 10, 0.7);
        assert_eq!(id, -1, "Should fail on oversized prompt");
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::InvalidInput as i32);
    }

    #[test]
    fn test_poll_result_unknown_id() {
        let result = pcai_poll_result(999_999);
        assert_eq!(result.status, -1, "Unknown ID should return status -1");
        assert!(result.text.is_null());
    }

    #[test]
    fn test_cancel_unknown_id() {
        let rc = pcai_cancel(999_999);
        assert_eq!(rc, -1, "Cancelling an unknown ID should return -1");
    }

    #[test]
    fn test_async_result_repr_c() {
        // Ensure PcaiAsyncResult has the expected field layout for FFI callers.
        // repr(C) on 64-bit: i32 (4 bytes) + 4 bytes padding + pointer (8 bytes) = 16 bytes.
        let expected_size = if std::mem::size_of::<*mut c_char>() == 8 {
            16 // 64-bit: 4 + 4 padding + 8
        } else {
            8 // 32-bit: 4 + 4
        };
        assert_eq!(
            std::mem::size_of::<PcaiAsyncResult>(),
            expected_size,
            "PcaiAsyncResult layout must match expected C ABI size"
        );
    }

    #[test]
    fn test_version_returns_valid_string() {
        let ptr = pcai_version();
        assert!(!ptr.is_null());
        let cstr = unsafe { CStr::from_ptr(ptr) };
        let version = cstr.to_str().expect("version should be valid UTF-8");
        assert!(!version.is_empty());
        // Version should look like a semver string (contains at least one dot)
        assert!(version.contains('.'), "version should contain a dot: {}", version);
    }

    #[test]
    fn test_free_string_null_safe() {
        // Calling pcai_free_string with null should not crash
        pcai_free_string(std::ptr::null_mut());
    }

    #[test]
    fn test_clear_error_resets_state() {
        set_last_error_with_code("some error", PcaiErrorCode::BackendError);
        assert!(!pcai_last_error().is_null());
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::BackendError as i32);

        clear_last_error();
        assert!(pcai_last_error().is_null());
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::Success as i32);
    }

    #[test]
    fn test_error_code_invalid_input() {
        clear_last_error();
        set_last_error_with_code("bad input", PcaiErrorCode::InvalidInput);
        assert_eq!(pcai_last_error_code(), PcaiErrorCode::InvalidInput as i32);
        assert_eq!(pcai_last_error_code(), -3);
    }
}
