#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Creates a scheduled task to auto-start RAG-Redis Docker containers at logon.
.DESCRIPTION
    Part of System Configuration Improvement Plan - Phase 5
    Registers a scheduled task that starts the RAG-Redis Docker stack at user logon.
.EXAMPLE
    .\Setup-RAGRedisAutoStart.ps1
    Run as administrator to create the scheduled task.
#>

[CmdletBinding()]
param(
    [string]$TaskName = "RAG-Redis-AutoStart",
    [string]$DockerComposePath = "C:\codedev\llm\rag-redis",
    [switch]$Remove
)

# Verify Docker Compose file exists
if (-not (Test-Path "$DockerComposePath\docker-compose.yml")) {
    Write-Error "Docker Compose file not found: $DockerComposePath\docker-compose.yml"
    exit 1
}

# Remove task if requested
if ($Remove) {
    $existingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existingTask) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Removed scheduled task: $TaskName" -ForegroundColor Yellow
    } else {
        Write-Host "Task not found: $TaskName" -ForegroundColor DarkGray
    }
    exit 0
}

# Check if task already exists
$existingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existingTask) {
    Write-Host "Task already exists: $TaskName" -ForegroundColor Yellow
    Write-Host "Current state: $($existingTask.State)" -ForegroundColor Cyan
    Write-Host "Use -Remove to unregister, then run again to recreate." -ForegroundColor DarkGray
    exit 0
}

# Create the startup script
$startupScript = @'
# RAG-Redis Auto-Start Script
# Generated by Setup-RAGRedisAutoStart.ps1

$logPath = "$env:USERPROFILE\.machine\logs\rag-redis-autostart.log"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# Ensure log directory exists
New-Item -ItemType Directory -Path (Split-Path $logPath) -Force -ErrorAction SilentlyContinue | Out-Null

# Function to write log
function Write-AutoStartLog {
    param([string]$Message)
    "$timestamp - $Message" | Add-Content -Path $logPath
}

Write-AutoStartLog "=== RAG-Redis Auto-Start Initiated ==="

# Wait for Docker to be ready
$maxWait = 120
$waited = 0
while ($waited -lt $maxWait) {
    $dockerInfo = docker info 2>&1
    if ($LASTEXITCODE -eq 0) {
        Write-AutoStartLog "Docker is ready after ${waited}s"
        break
    }
    Start-Sleep -Seconds 5
    $waited += 5
}

if ($waited -ge $maxWait) {
    Write-AutoStartLog "ERROR: Docker not ready after ${maxWait}s - aborting"
    exit 1
}

# Start RAG-Redis containers
Set-Location "DOCKER_COMPOSE_PATH"
Write-AutoStartLog "Starting docker-compose in: $(Get-Location)"

$result = docker-compose up -d redis rag-mcp-server 2>&1
Write-AutoStartLog "docker-compose output: $result"

# Verify containers started
Start-Sleep -Seconds 10
$redisStatus = docker inspect --format='{{.State.Status}}' rag-redis-backend 2>&1
$mcpStatus = docker inspect --format='{{.State.Status}}' rag-mcp-server 2>&1

Write-AutoStartLog "Container status - Redis: $redisStatus, MCP: $mcpStatus"

if ($redisStatus -eq "running") {
    Write-AutoStartLog "SUCCESS: RAG-Redis started successfully"
} else {
    Write-AutoStartLog "WARNING: Redis container not running"
}
'@

# Replace placeholder with actual path
$startupScript = $startupScript.Replace("DOCKER_COMPOSE_PATH", $DockerComposePath)

# Save startup script
$scriptPath = "$env:USERPROFILE\bin\Start-RAGRedis.ps1"
$startupScript | Set-Content -Path $scriptPath -Force
Write-Host "Created startup script: $scriptPath" -ForegroundColor Green

# Create scheduled task
$action = New-ScheduledTaskAction -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$scriptPath`""

$trigger = New-ScheduledTaskTrigger -AtLogon -User $env:USERNAME

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10) `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1)

$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

Register-ScheduledTask -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Principal $principal `
    -Description "Auto-starts RAG-Redis Docker containers at user logon" | Out-Null

Write-Host ""
Write-Host "Created scheduled task: $TaskName" -ForegroundColor Green
Write-Host "Trigger: At user logon ($env:USERNAME)" -ForegroundColor Cyan
Write-Host "Action: Start RAG-Redis Docker containers" -ForegroundColor Cyan
Write-Host ""
Write-Host "To test manually: .\Start-RAGRedis.ps1" -ForegroundColor DarkGray
Write-Host "To remove: .\Setup-RAGRedisAutoStart.ps1 -Remove" -ForegroundColor DarkGray
