<#
.SYNOPSIS
Registers the UDM drive-stack startup scheduled task.

.DESCRIPTION
Creates or updates the logon scheduled task that runs Start-UDMDriveStack.ps1
with delayed startup, working directory, retry policy, execution timeout, and
Application event-log source setup.

.PARAMETER DryRun
Preview the task registration without changing Task Scheduler or event-log
sources. The long CLI form `--DryRun` is also accepted.

.PARAMETER WhatIf
Preview the task registration without changing Task Scheduler or event-log
sources. Kept for existing callers; equivalent to DryRun.

.PARAMETER Help
Print script help and exit. The aliases `-h` and `--help` are also accepted.
#>
param(
    [string]$TaskName = "UnifiUdmDriveStackStartup",
    [string]$TargetHost = "192.168.1.1",
    [string]$SmbMountPath = "F:\udm_smb",
    [string]$RcloneMountPath = "W:\udm_rclone",
    [string]$EventSource = "UDMDriveStack",
    [int]$StartupDelaySeconds = 120,
    [int]$RestartCount = 3,
    [int]$RestartIntervalMinutes = 1,
    [int]$ExecutionTimeLimitMinutes = 15,
    [switch]$RunNow,
    [switch]$Unregister,
    [switch]$WhatIf,
    [switch]$DryRun,
    [Alias('h', '?')]
    [switch]$Help,
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$CliArgs
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$CliArgs = @($CliArgs | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
if (@($CliArgs) -contains '--help') {
    $Help = $true
    $CliArgs = @($CliArgs | Where-Object { $_ -ne '--help' })
}
if (@($CliArgs) -contains '--DryRun') {
    $DryRun = $true
    $CliArgs = @($CliArgs | Where-Object { $_ -ne '--DryRun' })
}
if ($DryRun) {
    $WhatIf = $true
}
if ($Help) {
    $helpMatch = [regex]::Match((Get-Content -LiteralPath $PSCommandPath -Raw), '(?s)<#\s*(.*?)\s*#>')
    if ($helpMatch.Success) { $helpMatch.Groups[1].Value.Trim() } else { Get-Help -Detailed $PSCommandPath }
    return
}
if (@($CliArgs).Count -gt 0) {
    throw "Unknown CLI argument(s): $($CliArgs -join ', ')"
}

function Write-Step {
    param([string]$Message)
    Write-Host "[udm-task] $Message"
}

function ConvertTo-Iso8601Duration {
    param([timespan]$Duration)

    if ($Duration.TotalSeconds -lt 1) {
        return "PT0S"
    }

    $parts = "PT"
    if ($Duration.Hours -gt 0) {
        $parts += "$($Duration.Hours)H"
    }
    if ($Duration.Minutes -gt 0) {
        $parts += "$($Duration.Minutes)M"
    }
    if ($Duration.Seconds -gt 0) {
        $parts += "$($Duration.Seconds)S"
    }
    return $parts
}

function Ensure-EventSource {
    param([string]$Source)

    try {
        if (-not [System.Diagnostics.EventLog]::SourceExists($Source)) {
            if ($WhatIf) {
                Write-Step "would create Application event source: $Source"
                return
            }
            New-EventLog -LogName Application -Source $Source -ErrorAction Stop
            Write-Step "created Application event source: $Source"
            return
        }
        Write-Step "Application event source exists: $Source"
    }
    catch {
        Write-Step "WARNING: unable to verify/create Application event source '$Source': $($_.Exception.Message)"
    }
}

if ($Unregister) {
    if ($WhatIf) {
        Write-Step "would unregister scheduled task: $TaskName"
        return
    }
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Write-Step "scheduled task removed: $TaskName"
    return
}

$scriptPath = Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) "Start-UDMDriveStack.ps1"
if (-not (Test-Path $scriptPath)) {
    throw "Missing startup script: $scriptPath"
}

$workingDirectory = Split-Path -Parent $scriptPath
$description = @(
    "Starts the UDM drive stack after logon with transcript, structured logs,",
    "Windows event-log events, dependency validation, bounded retries, and",
    "explicit exit codes. Generated by Register-UDMDriveStartupTask.ps1."
) -join " "

$argList = @(
    "-NoProfile",
    "-WindowStyle", "Hidden",
    "-ExecutionPolicy", "Bypass",
    "-File", "`"$scriptPath`"",
    "-TargetHost", $TargetHost,
    "-SmbMountPath", "`"$SmbMountPath`"",
    "-RcloneMountPath", "`"$RcloneMountPath`"",
    "-EventSource", "`"$EventSource`"",
    "-EnsureSmbEnabled"
) -join " "

$action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument $argList -WorkingDirectory $workingDirectory
$trigger = New-ScheduledTaskTrigger -AtLogOn
$trigger.Delay = ConvertTo-Iso8601Duration -Duration (New-TimeSpan -Seconds $StartupDelaySeconds)

$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" -LogonType Interactive -RunLevel Highest
$settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew `
    -RestartCount $RestartCount `
    -RestartInterval (New-TimeSpan -Minutes $RestartIntervalMinutes) `
    -ExecutionTimeLimit (New-TimeSpan -Minutes $ExecutionTimeLimitMinutes)

Ensure-EventSource -Source $EventSource

if ($WhatIf) {
    Write-Step "would register scheduled task: $TaskName"
    Write-Host "     description: $description"
    Write-Host "     trigger: at logon, delayed $StartupDelaySeconds seconds"
    Write-Host "     action: powershell.exe $argList"
    Write-Host "     start in: $workingDirectory"
    Write-Host "     retries: $RestartCount every $RestartIntervalMinutes minute(s)"
    Write-Host "     timeout: $ExecutionTimeLimitMinutes minutes"
    return
}

Register-ScheduledTask `
    -TaskName $TaskName `
    -Action $action `
    -Trigger $trigger `
    -Principal $principal `
    -Settings $settings `
    -Description $description `
    -Force | Out-Null

Write-Step "scheduled task registered: $TaskName"
Write-Host "     trigger: at logon, delayed $StartupDelaySeconds seconds"
Write-Host "     start in: $workingDirectory"
Write-Host "     retries: $RestartCount every $RestartIntervalMinutes minute(s)"
Write-Host "     timeout: $ExecutionTimeLimitMinutes minutes"
Write-Host "     event source: $EventSource"

if ($RunNow) {
    Start-ScheduledTask -TaskName $TaskName
    Write-Step "scheduled task started: $TaskName"
}
